# Assignment DAY 3


# Question 1

In [1]:
import numpy as np
np.arange(2, 50, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [2]:
listA = []
n = int(input("Enter number of elements in the list : "))
for i in range(0, n):
   print("Enter element No-{}: ".format(i+1))
   elm = int(input())
   listA.append(elm) 
print("The entered list is: \n",listA)

listB= []
n = int(input("Enter number of elements in the list : "))
for i in range(0, n):
   print("Enter element No-{}: ".format(i+1))
   elm = int(input())
   listB.append(elm)
print("The entered list is: \n",listB)

Enter number of elements in the list : 5
Enter element No-1: 
45
Enter element No-2: 
2
Enter element No-3: 
58
Enter element No-4: 
665
Enter element No-5: 
44
The entered list is: 
 [45, 2, 58, 665, 44]
Enter number of elements in the list : 5
Enter element No-1: 
266
Enter element No-2: 
555
Enter element No-3: 
612
Enter element No-4: 
225
Enter element No-5: 
8
The entered list is: 
 [266, 555, 612, 225, 8]


In [3]:
a = np.array([listA])
b = np.array([listB])
print(a)
print(b)

[[ 45   2  58 665  44]]
[[266 555 612 225   8]]


In [4]:
arr = np.concatenate((a , b))
print(arr)


[[ 45   2  58 665  44]
 [266 555 612 225   8]]


In [6]:
arr_srt = np.array([ arr] )
print(np.sort(arr_srt))

[[[  2  44  45  58 665]
  [  8 225 266 555 612]]]


# Question 3

In [12]:
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


# Question 4


In [17]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)
print("Dimensions: ", arr_1d.ndim)

print()

arr_2d = np.reshape(arr_1d, (-1, 2))
print(arr_2d)
print("Dimensions: ", arr_2d.ndim)

[1 2 3 4]
Dimensions:  1

[[1 2]
 [3 4]]
Dimensions:  2


# OR

In [41]:
import numpy as np

In [42]:
x = np.array([1, 2])
x.shape

(2,)

In [43]:
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

In [44]:
y.shape

(1, 2)

In [45]:
y = np.expand_dims(x, axis=1)
y


array([[1],
       [2]])

In [46]:
y.shape

(2, 1)

In [51]:
y = np.expand_dims(x, axis=(0, 1))
y

array([[[1, 2]]])

In [52]:
y = np.expand_dims(x, axis=(2, 0))
y


array([[[1],
        [2]]])

# Question 5

In [56]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [57]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


# Question 6

In [66]:
# USE set() AND len() TO COUNT UNIQUE VALUES IN A LIST

a_list = [1, 1, 2, 2, 3]
a_set = set(listA)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

3
